- name: Build and push docker image
  hosts: build_host
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure in DockerHub is login
      docker_login:
        username:
          - "{{ DockerHub_user }}"
        password:
          - "{{ DockerHub_pass }}"